blueprint:
  name: Aqara W100 Sync (ZHA)
  description: |-
    * **Climate Sync:** Syncs the W100 with the linked climate entity.
    * **External Sensor Sync:** Displays temperature and humidity from the linked climate entity or external sensors.
    * **W100 Action Failure Recovery:** Restores or adjusts W100 settings when applying a change to the linked climate entity fails.
  
    **W100 device settings:** Enable **Thermostat control** for climate sync and **External sensor** for sensor sync. These features work independently.

    ⚠️ **Requires [custom quirk](https://github.com/nokside/ha-toolbox/blob/main/quirks/aqara_w100.py)**
  domain: automation
  source_url: https://raw.githubusercontent.com/nokside/ha-toolbox/main/blueprints/automation/aqara_w100.yaml
  author: nokside
  input:
    w100_climate:
      name: Aqara W100
      description: Required for climate sync and/or external sensor sync.
      selector:
        entity:
          filter:
            - integration: zha
              domain: climate
    linked_climate:
      name: Linked climate entity
      default: []
      selector:
        entity:
          filter:
            - domain: climate
    w100_recovery:
      name: W100 action failure recovery
      description: Restore or adjust W100 settings when applying a change to the linked climate entity fails.
      default: true
      selector:
        boolean:
    resync_interval:
      name: Resync interval
      description: Choose how often to resync the W100.
      default: "*"
      selector:
        select:
          mode: dropdown
          options:
            - label: Disabled
              value: "*"
            - label: Every 15 minutes
              value: "/15"
            - label: Every 30 minutes
              value: "/30"
            - label: Every hour
              value: "0"
    external_sensor_sync:
      name: External sensor sync
      icon: mdi:thermometer-lines
      collapsed: true
      input:
        linked_climate_temp_hum:
          name: Linked climate temperature and humidity
          default: false
          selector:
            boolean:
  
        temperature_sensor:
          name: Temperature sensor
          description: Overrides the linked climate temperature when selected.
          default: []
          selector:
            entity:
              filter:
                - domain: sensor
                  device_class: temperature
  
        humidity_sensor:
          name: Humidity sensor
          description: Overrides the linked climate humidity when selected.
          default: []
          selector:
            entity:
              filter:
                - domain: sensor
                  device_class: humidity

mode: queued
max_exceeded: silent

trace:
  stored_traces: 10

trigger_variables:
  _linked: !input linked_climate
  _temp_sensor: !input temperature_sensor
  _hum_sensor: !input humidity_sensor
  _linked_climate_temp_hum: !input linked_climate_temp_hum
  _resync_interval: !input resync_interval

triggers:
  - trigger: time_pattern
    minutes: !input resync_interval
    id: resync
    enabled: "{{ _resync_interval != '*' }}"
  - trigger: state
    entity_id: !input w100_climate
    id: mode
    enabled: "{{ _linked != [] }}"
    not_from: [unavailable, unknown]
    not_to: [unavailable, unknown]
      
  - trigger: state
    entity_id: !input linked_climate
    id: mode
    enabled: "{{ _linked != [] }}"
    not_from: [unavailable, unknown]
    not_to: [unavailable, unknown]

  - trigger: state
    entity_id: !input w100_climate
    id: temperature
    enabled: "{{ _linked != [] }}"
    attribute: temperature

  - trigger: state
    entity_id: !input w100_climate
    id: fan
    enabled: "{{ _linked != [] }}"
    attribute: fan_mode

  - trigger: state
    entity_id: !input linked_climate
    id: temperature
    enabled: "{{ _linked != [] }}"
    attribute: temperature

  - trigger: state
    entity_id: !input linked_climate
    id: fan
    enabled: "{{ _linked != [] }}"
    attribute: fan_mode

  - trigger: state
    entity_id: !input w100_climate
    from: [unavailable, unknown]
    id: resync
    enabled: >-
      {{ _linked != []
         or _temp_sensor != []
         or _hum_sensor != [] }}

  - trigger: state
    entity_id: !input linked_climate
    from: [unavailable, unknown]
    id: resync
    enabled: "{{ _linked != [] }}"

  - trigger: state
    entity_id: !input linked_climate
    attribute: current_temperature
    id: ext_temp
    enabled: "{{ _linked_climate_temp_hum is true and _temp_sensor == [] and _linked != [] }}"

  - trigger: state
    entity_id: !input linked_climate
    attribute: current_humidity
    id: ext_hum
    enabled: "{{ _linked_climate_temp_hum is true and _hum_sensor == [] and _linked != [] }}"

  - trigger: state
    entity_id: !input temperature_sensor
    id: ext_temp
    enabled: "{{ _temp_sensor != [] }}"
    not_to: [unavailable, unknown]

  - trigger: state
    entity_id: !input humidity_sensor
    id: ext_hum
    enabled: "{{ _hum_sensor != [] }}"
    not_to: [unavailable, unknown]

variables:
  w100: !input w100_climate
  linked: !input linked_climate
  linked_climate_temp_hum: !input linked_climate_temp_hum
  temp_sensor: !input temperature_sensor
  hum_sensor: !input humidity_sensor
  w100_recovery: !input w100_recovery

conditions:
  - alias: Check if W100 is available
    condition: template
    value_template: "{{ has_value(w100) }}"

actions:
  - alias: Sync climate
    if:
      - condition: trigger
        id: [fan, mode, temperature, resync]
      - condition: template
        value_template: "{{ linked != [] and has_value(linked) }}"
    then:
      - alias: Set source, target
        variables:
          source: "{{ linked if trigger.id == 'resync' else trigger.entity_id }}"
          target: "{{ linked if source == w100 else w100 }}"

      - alias: HVAC mode
        if:
          - condition: trigger
            id: [mode, resync]
        then:
          - variables:
              mode: >-
                {{ states(source)
                   if trigger.id == 'resync'
                   else trigger.to_state.state }}

          - condition: template
            value_template: "{{ mode != states(target) }}"

          - variables:
              needs_recovery: true

          - alias: Set HVAC mode
            continue_on_error: true
            sequence:
              - action: climate.set_hvac_mode
                target:
                  entity_id: "{{ target }}"
                data:
                  hvac_mode: "{{ mode }}"

              - variables:
                  needs_recovery: false

          - alias: Recover W100 HVAC mode
            if:
              - condition: template
                value_template: >-
                  {{ w100_recovery
                     and source == w100
                     and needs_recovery }}
            then:
              - action: climate.set_hvac_mode
                target:
                  entity_id: "{{ w100 }}"
                data:
                  hvac_mode: "{{ states(linked) }}"

      - alias: Temperature
        if:
          - condition: trigger
            id: [temperature, resync]
        then:
          - variables:
              temperature: >-
                {{ state_attr(source, 'temperature')
                   if trigger.id == 'resync'
                   else trigger.to_state.attributes.get('temperature') }}
              mode: >-
                {{ states(source)
                   if trigger.id == 'resync'
                   else trigger.to_state.state }}

          - condition: template
            value_template: >-
              {{ temperature is number
                 and temperature != state_attr(target, 'temperature')
                 and mode == states(target) }}

          - variables:
              needs_recovery: true

          - alias: Set temperature
            continue_on_error: true
            sequence:
              - action: climate.set_temperature
                target:
                  entity_id: "{{ target }}"
                data:
                  temperature: "{{ temperature }}"

              - variables:
                  needs_recovery: false

          - alias: Clamp W100 temperature
            if:
              - condition: template
                value_template: >-
                  {{ w100_recovery
                     and source == w100
                     and needs_recovery
                     and state_attr(linked, 'min_temp') is number
                     and state_attr(linked, 'max_temp') is number }}
            then:
              - action: climate.set_temperature
                target:
                  entity_id: "{{ w100 }}"
                data:
                  temperature: >-
                    {% set minimum = state_attr(linked, 'min_temp') %}
                    {% set maximum = state_attr(linked, 'max_temp') %}
                    {{ max(minimum, min(temperature, maximum)) }}

      - alias: Fan mode
        if:
          - condition: trigger
            id: [fan, resync]
        then:
          - variables:
              fan_mode: >-
                {{ state_attr(source, 'fan_mode')
                   if trigger.id == 'resync'
                   else trigger.to_state.attributes.get('fan_mode') }}

          - condition: template
            value_template: >-
              {{ fan_mode is not none
                 and fan_mode != state_attr(target, 'fan_mode') }}

          - variables:
              needs_recovery: true

          - alias: Set fan mode
            continue_on_error: true
            sequence:
              - action: climate.set_fan_mode
                target:
                  entity_id: "{{ target }}"
                data:
                  fan_mode: "{{ fan_mode }}"

              - variables:
                  needs_recovery: false

          - alias: Recover W100 fan mode
            if:
              - condition: template
                value_template: >-
                  {{ w100_recovery
                     and source == w100
                     and needs_recovery }}
            then:
              - action: climate.set_fan_mode
                target:
                  entity_id: "{{ w100 }}"
                data:
                  fan_mode: "{{ state_attr(linked, 'fan_mode') | default('off', true) }}"

  - alias: Sync external temperature
    continue_on_error: true
    if:
      - condition: trigger
        id: [ext_temp, resync]
      - condition: or
        conditions:
          - condition: template
            value_template: "{{ linked_climate_temp_hum is true and has_value(linked) }}"
          - condition: template
            value_template: "{{ temp_sensor != [] }}"
    then:
      - alias: Define source
        variables:
          ext_temp_data: >-
            {{ states(temp_sensor)
               if temp_sensor != []
               else state_attr(linked, 'current_temperature') }}
          ext_temp_entity: >-
            {{ device_entities(device_id(w100))
               | select('match', '^number\.')
               | select('search', 'external_temperature')
               | first
               | default('') }}

      - condition: template
        value_template: >-
          {{ is_number(ext_temp_data)
             and is_number(states(ext_temp_entity))
             and ext_temp_data | float | round(1) != states(ext_temp_entity) | float | round(1) }}

      - alias: Set value
        action: number.set_value
        target:
          entity_id: "{{ ext_temp_entity }}"
        data:
          value: "{{ ext_temp_data }}"

  - alias: Sync external humidity
    continue_on_error: true
    if:
      - condition: trigger
        id: [ext_hum, resync]
      - condition: or
        conditions:
          - condition: template
            value_template: "{{ linked_climate_temp_hum is true and has_value(linked) }}"
          - condition: template
            value_template: "{{ hum_sensor != [] }}"
    then:
      - alias: Define source
        variables:
          ext_hum_data: >-
            {{ states(hum_sensor)
               if hum_sensor != []
               else state_attr(linked, 'current_humidity') }}
          ext_hum_entity: >-
            {{ device_entities(device_id(w100))
               | select('match', '^number\.')
               | select('search', 'external_humidity')
               | first
               | default('') }}

      - condition: template
        value_template: |-
          {{ is_number(ext_hum_data)
             and is_number(states(ext_hum_entity))
             and ext_hum_data | int != states(ext_hum_entity) | int }}

      - alias: Set value
        action: number.set_value
        target:
          entity_id: "{{ ext_hum_entity }}"
        data:
          value: "{{ ext_hum_data }}"
